### ISSUE TITLE
There was an error exporting the html report

### ISSUE THREAD

**Issue by huangyuan666** [enkomio/Taipan#10]
![image](https://user-images.githubusercontent.com/24352334/56020553-febf9c00-5d39-11e9-985c-a28474edec53.png)
![image](https://user-images.githubusercontent.com/24352334/56020583-0e3ee500-5d3a-11e9-8e6e-9f021500ba38.png)
There was an error exporting the html report

**Comment by enkomio** [comment]
Hi,

could you please tell me which version of Taipan was used? Also, could you please send an email to info@taipansec.com with the generated json report (from the screenshot I see that the name is 3_http_192_168_1_126_.json)?

Thanks,
Antonio

**Comment by enkomio** [comment]
Hi,

a new version has been released that should fix this problem. You can download it from the Download web page.
