### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by elbae** [enkomio/Taipan#11]
Hi, the ufficial doc is not available.

![image](https://user-images.githubusercontent.com/19212922/73930366-ac59f800-48d6-11ea-9e04-243b5978d884.png)

![image](https://user-images.githubusercontent.com/19212922/73930423-bf6cc800-48d6-11ea-9a25-0baa4dcaf79f.png)

**Comment by enkomio** [comment]
Hi @elbae,

thanks for pointing this out. At one point I decided to put the documentation on the authenticated part of the website, which it is accessible only to customers.

I think that this choice can now be reverted to open the documentation to everyone.

I'll modify the website to allow the access to everyone.

**Comment by enkomio** [comment]
Hi @elbae,

now it should be accessible.
