### ISSUE TITLE
Can not open web interface

### ISSUE THREAD

**Issue by elliot-bia** [enkomio/Taipan#8]
Hi, I had downloaded this scanner, but I can't find how to open web interface. Does it only show in Pro edition? Thanks

**Comment by enkomio** [comment]
Hi, yes you are right. The Web Interface and other enterprise features are only available in the Pro version. For more information on the Pro version you can visit https://taipansec.com/index

**Comment by elliot-bia** [comment]
Can I get Pro version demo? Do I need to pay for a trial? Or can I try it for a few days for free?
